In [2]:
# Q2
import sympy as sym

t = sym.Symbol('t')
T = sym.Symbol('T')
a0, a1, a2, a3, a4, a5 = sym.symbols('a0 a1 a2 a3 a4 a5')

s = a0 + a1*t + a2*t**2 + a3*t**3 + a4*t**4 + a5*t**5
print("s(t) = ")
display(s)
sdot = s.diff(t)
print("s'(t) = ")
display(sdot)
sddot = sdot.diff(t)
print("s''(t) = ")
display(sddot)

# Compute the coefficients of the polynomial
s0_eq = s.subs(t, 0)
sT_eq = s.subs(t, T)
sdot0_eq = sdot.subs(t, 0)
sdotT_eq = sdot.subs(t, T)
sddot0_eq = sddot.subs(t, 0)
sddotT_eq = sddot.subs(t, T)

eq1 = sym.Eq(s0_eq, 0)
eq2 = sym.Eq(sT_eq, 1)
eq3 = sym.Eq(sdot0_eq, 0)
eq4 = sym.Eq(sdotT_eq, 0)
eq5 = sym.Eq(sddot0_eq, 0)
eq6 = sym.Eq(sddotT_eq, 0)

soln = sym.solve([eq1, eq2, eq3, eq4, eq5, eq6], (a0, a1, a2, a3, a4, a5))
print("Solution:")
display(soln)

s(t) = 


a0 + a1*t + a2*t**2 + a3*t**3 + a4*t**4 + a5*t**5

s'(t) = 


a1 + 2*a2*t + 3*a3*t**2 + 4*a4*t**3 + 5*a5*t**4

s''(t) = 


2*a2 + 6*a3*t + 12*a4*t**2 + 20*a5*t**3

Solution:


{a0: 0, a1: 0, a2: 0, a3: 10/T**3, a4: -15/T**4, a5: 6/T**5}

In [3]:
# Q5
import modern_robotics as mr
print("S(3) = ",mr.QuinticTimeScaling(5,3))

S(3) =  0.6825599999999996


In [4]:
# Q6
import numpy as np
Xstart = np.array([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]])
Xend = np.array([[0, 0, 1, 1],
                 [1, 0, 0, 2],
                 [0, 1, 0, 3],
                 [0, 0, 0, 1]])
q6_out = mr.ScrewTrajectory(Xstart, Xend, 10, 10, 3)
print("Q6 output:") 
print(q6_out[-2])

Q6 output:
[[ 0.04229152 -0.04057269  0.99828116  0.93313173]
 [ 0.99828116  0.04229152 -0.04057269  1.97198558]
 [-0.04057269  0.99828116  0.04229152  2.88912137]
 [ 0.          0.          0.          1.        ]]


In [6]:
# Q7
q7_out = mr.CartesianTrajectory(Xstart, Xend, 10, 10, 5)
print("Q7 output:")
print(q7_out[-2])

Q7 output:
[[ 0.01404133 -0.01384686  0.99980553  0.98846721]
 [ 0.99980553  0.01404133 -0.01384686  1.97693441]
 [-0.01384686  0.99980553  0.01404133  2.96540162]
 [ 0.          0.          0.          1.        ]]


https://medium.com/@14prakash/back-propagation-is-very-simple-who-made-it-complicated-97b794c97e5c
https://medium.com/@14prakash/back‐propagation‐is‐very‐simple‐who‐made‐it‐complicated‐97b794c97e5c