# ME449 - Homework 3 - Zhengyang Kris Weng Submission

In [4]:
import numpy as np
import modern_robotics as mr
from tqdm import tqdm
import ur5_parameters
ur5 = ur5_parameters.UR5()

## Part0: Puppet function

## Part 1: Simulating a falling robot. 
In the first part, the robot will fall in gravity without
damping or the external spring (joint damping and spring stiffness are set to zero). Since there is
no damping or friction, the total energy of the robot (kinetic plus potential) should remain constant
during motion. Gravity is g = 9.81 m/s2 in the −ˆzs-direction, i.e., gravity acts downward.
Simulate the robot falling from rest at the home configuration for five seconds. The output data
should be saved as a .csv file, where each of the N rows has six numbers separated by commas.
This .csv file is suitable for animation with the CoppeliaSim UR5 csv animation scene. Adjust
the animation scene playback speed (“Time Multiplier”) so it takes roughly five seconds of wall
clock time to play your csv file. You can evaluate if your simulation is preserving total energy by
visually checking if the robot appears to swing to the same height (same potential energy) each
swing. Choose values of dt (a) where the energy appears nearly constant (without choosing dt
unnecessarily small) and (b) where the energy does not appear constant (because your timestep
is too coarse). Capture a video for each case and note the dt chosen for each case. Explain how
you would calculate the total energy of the robot at each timestep if you wanted to plot the total
energy to confirm that your simulation approximately preserves it.

In [5]:
# Puppet function:
def puppet_q1(thetalist, dthetalist, g, Mlist, Slist, Glist, t, dt, damping, stiffness, restLength):
    """
    Simulate a robot under damping and spring reaction. Q1: free falling in gravity

    Args:
        thetalist (np.array): n-vector of initial joint angles (rad)
        dthetalist (np.array): n-vector of initial joint velocities (rad/s)
        g (np.array): 3-vector of gravity in s frame (m/s^2)
        Mlist (np.array): 8 frames of link configuration at home pose
        Slist (np.array): 6-vector of screw axes at home configuration
        Glist (np.array): Spatial inertia matrices of the links
        t (float): total simulation time (s)
        dt (float): simulation time step (s)
        damping (float): viscous damping coefficient (Nmn/rad)
        stiffness (float): spring stiffness coefficient (N/m)
        restLength (float): length of the spring at rest (m)
    Returns:
        thetamat (np.array): N x n matrix of joint angles (rad). Each row is a set of joint angles
        dthetamat (np.array): N x n matrix of joint velocities (rad/s). Each row is a set of joint velocities
    """
    # Initialize 
    N = int(t/dt)
    n = len(thetalist)
    thetamat = np.zeros((N + 1, n))
    dthetamat = np.zeros((N + 1, n))
    thetamat[0] = thetalist
    dthetamat[0] = dthetalist

    for i in tqdm(range(N)):
        i_acc = mr.ForwardDynamics(thetalist, dthetalist, np.zeros(n), g, np.zeros(n), Mlist, Glist, Slist) 
        i_pos, i_vel = mr.EulerStep(thetalist, dthetalist, i_acc, dt)
        thetamat[i + 1] = i_pos
        dthetamat[i + 1] = i_vel

        # Update
        thetalist = i_pos
        dthetalist = i_vel
    
    return thetamat, dthetamat

In [6]:
q1_thetalist0 = np.array([0, 0, 0, 0, 0, 0])
q1_dthetalist0 = np.array([0, 0, 0, 0, 0, 0])
g = np.array([0, 0, -9.81])

q1_thetamat, _ = puppet_q1(q1_thetalist0, q1_dthetalist0, g, ur5.Mlist, ur5.Slist, ur5.Glist, 5, 0.001, 0, 0, 0)

# Save to csv file
np.savetxt('q1_thetamat.csv', q1_thetamat, delimiter=',')

100%|██████████| 5000/5000 [00:32<00:00, 156.21it/s]


In [7]:
q1_thetamat_coarse, _ = puppet_q1(q1_thetalist0, q1_dthetalist0, g, ur5.Mlist, ur5.Slist, ur5.Glist, 5, 0.01, 0, 0, 0)

# Save to csv file
np.savetxt('q1_thetamat_coarse.csv', q1_thetamat_coarse, delimiter=',')

100%|██████████| 500/500 [00:03<00:00, 156.37it/s]


Loooking at video part1a and part1b.mp4, we can see that energy is not conserved due to error in numerical integration when timestep is too coarse. A good measure of total system energy would be the Hamiltonian of the system, as a sum of potential energy and kinetic energy of each link. By plotting the trend of Hamiltonian of each configuration in the trajectory, this will visualize the preservation of energy in the system. [TODO: IMPLEMENT COMPUTE H WHEN HAVE TIME]

## Part 2: Adding damping. 
Now experiment with different damping coefficients as the robot
falls from the home configuration. Damping causes a torque at each joint equal to the negative of
the joint rate times the damping. Create two videos showing that (a) when you choose damping to
be positive, the robot loses energy as it swings, and (b) when you choose damping to be negative,
the robot gains energy as it swings. Use t = 5 s and dt = 0.01 s, and for the case of positive
damping, the damping coefficient should almost (but not quite) bring the robot to rest by the end
of the video. Do you see any strange behavior in the simulation if you choose the damping constant
to be a large positive value? Can you explain it? How would this behavior change if you chose
shorter simulation timesteps?

In [8]:
def puppet_q2(thetalist, dthetalist, g, Mlist, Slist, Glist, t, dt, damping, stiffness, restLength):
    """
    Simulate a robot under damping and spring reaction. Q2: Adding damping to robot. Damping causes a tau = - dtheta * damping

    Args:
        thetalist (np.array): n-vector of initial joint angles (rad)
        dthetalist (np.array): n-vector of initial joint velocities (rad/s)
        g (np.array): 3-vector of gravity in s frame (m/s^2)
        Mlist (np.array): 8 frames of link configuration at home pose
        Slist (np.array): 6-vector of screw axes at home configuration
        Glist (np.array): Spatial inertia matrices of the links
        t (float): total simulation time (s)
        dt (float): simulation time step (s)
        damping (float): viscous damping coefficient (Nmn/rad)
        stiffness (float): spring stiffness coefficient (N/m)
        restLength (float): length of the spring at rest (m)
    Returns:
        thetamat (np.array): N x n matrix of joint angles (rad). Each row is a set of joint angles
        dthetamat (np.array): N x n matrix of joint velocities (rad/s). Each row is a set of joint velocities
    """
    # Initialize 
    N = int(t/dt)
    n = len(thetalist)
    thetamat = np.zeros((N + 1, n))
    dthetamat = np.zeros((N + 1, n))
    thetamat[0] = thetalist
    dthetamat[0] = dthetalist

    for i in tqdm(range(N)):
        tau_damping = - damping * dthetalist
        i_acc = mr.ForwardDynamics(thetalist, dthetalist, tau_damping, g, np.zeros(n), Mlist, Glist, Slist) 
        i_pos, i_vel = mr.EulerStep(thetalist, dthetalist, i_acc, dt)
        thetamat[i + 1] = i_pos
        dthetamat[i + 1] = i_vel

        # Update
        thetalist = i_pos
        dthetalist = i_vel
    
    return thetamat, dthetamat

In [9]:
q2_thetalist0 = np.array([0, 0, 0, 0, 0, 0])
q2_dthetalist0 = np.array([0, 0, 0, 0, 0, 0])
g = np.array([0, 0, -9.81])

q2_thetamat, _ = puppet_q2(q2_thetalist0, q2_dthetalist0, g, ur5.Mlist, ur5.Slist, ur5.Glist, 5, 0.01, 1.2, 0, 0)
# Save to csv file
np.savetxt('q2_thetamat.csv', q2_thetamat, delimiter=',')

100%|██████████| 500/500 [00:03<00:00, 156.30it/s]


In [10]:
q2_thetamat_neg, _ = puppet_q2(q2_thetalist0, q2_dthetalist0, g, ur5.Mlist, ur5.Slist, ur5.Glist, 5, 0.01, -0.02, 0, 0)
# Save to csv file
print(q2_thetamat_neg)
np.savetxt('q2_thetamat_neg.csv', q2_thetamat_neg, delimiter=',')

100%|██████████| 500/500 [00:03<00:00, 156.56it/s]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.57237340e-03 -2.87368129e-03  3.01307887e-04
   3.18411925e-22 -1.13423177e-18]
 ...
 [-3.07812861e-01 -9.92195181e+00  1.31700123e+01 -6.81968171e+00
  -8.36251555e-01  5.89264993e+01]
 [-3.02987560e-01 -1.00110250e+01  1.32499198e+01 -6.84260777e+00
  -8.76917115e-01  5.96387109e+01]
 [-2.97193787e-01 -1.00998345e+01  1.33216146e+01 -6.85772600e+00
  -9.17977817e-01  6.03581957e+01]]


In [11]:
q2_thetamat_large, _ = puppet_q2(q2_thetalist0, q2_dthetalist0, g, ur5.Mlist, ur5.Slist, ur5.Glist, 5, 0.01, 20, 0, 0)
# Save to csv file
print(q2_thetamat_large)
np.savetxt('q2_thetamat_large.csv', q2_thetamat_large, delimiter=',')

  0%|          | 0/500 [00:00<?, ?it/s]/usr/lib/python3/dist-packages/modern_robotics/core.py:927: RuntimeWarning: overflow encountered in multiply
  + np.dot(ad(Vi[:, i + 1]), Ai[:, i]) * dthetalist[i]
  3%|▎         | 17/500 [00:00<00:02, 165.73it/s]/usr/lib/python3/dist-packages/modern_robotics/core.py:143: RuntimeWarning: invalid value encountered in sin
  return np.eye(3) + np.sin(theta) * omgmat \
/usr/lib/python3/dist-packages/modern_robotics/core.py:144: RuntimeWarning: invalid value encountered in cos
  + (1 - np.cos(theta)) * np.dot(omgmat, omgmat)
/usr/lib/python3/dist-packages/modern_robotics/core.py:366: RuntimeWarning: invalid value encountered in multiply
  np.dot(np.eye(3) * theta \
/usr/lib/python3/dist-packages/modern_robotics/core.py:367: RuntimeWarning: invalid value encountered in cos
  + (1 - np.cos(theta)) * omgmat \
/usr/lib/python3/dist-packages/modern_robotics/core.py:368: RuntimeWarning: invalid value encountered in sin
  + (theta - np.sin(theta)) \
100%|████

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.57237340e-03 -2.87368129e-03  3.01307887e-04
   3.18411925e-22 -1.13423177e-18]
 ...
 [            nan             nan             nan             nan
              nan             nan]
 [            nan             nan             nan             nan
              nan             nan]
 [            nan             nan             nan             nan
              nan             nan]]


As I increase the magnitude of damping coefficient in the simulation, the function start to run into numerical stability issues and starts to produce nan values in output. This happend because of the numerical instability in the euler integration and the fact that coarse timestep landing next iteration on gradients amplifying such effect; as a result simulation output grew at an extremely fast rate and overflowed. Increasing granularity in timestep helps addressing this issue.

## Part 3: Adding a spring. 
Make gravity and damping zero and design referencePos to return
a constant springPos at (0, 1, 1) in the {s} frame. The spring’s restLength is zero. Experiment
with different stiffness values, and simulate the robot for t = 10 s and dt = 0.01 s starting from
the home configuration. (a) Capture a video for a choice of stiffness that makes the robot oscillate
a couple of times and record the stiffness value. Considering the system’s total energy, does the
motion of the robot make sense? What do you expect to happen to the total energy over time?
Describe the strange behavior you see if you choose the spring constant to be large; if you don’t
see any strange behavior, explain why. (b) Now add a positive damping to the simulation that
makes the arm nearly come to rest by the end of the video. For both videos, record the stiffness
and damping you used.

In [69]:
def puppet_q3(thetalist, dthetalist, g, Mlist, Slist, Glist, t, dt, damping, stiffness, restLength):
    """
    Simulate a robot under damping and spring reaction. Q3: Adding a static spring.

    Args:
        thetalist (np.array): n-vector of initial joint angles (rad)
        dthetalist (np.array): n-vector of initial joint velocities (rad/s)
        g (np.array): 3-vector of gravity in s frame (m/s^2)
        Mlist (np.array): 8 frames of link configuration at home pose
        Slist (np.array): 6-vector of screw axes at home configuration
        Glist (np.array): Spatial inertia matrices of the links
        t (float): total simulation time (s)
        dt (float): simulation time step (s)
        damping (float): viscous damping coefficient (Nmn/rad)
        stiffness (float): spring stiffness coefficient (N/m)
        restLength (float): length of the spring at rest (m)
    Returns:
        thetamat (np.array): N x n matrix of joint angles (rad). Each row is a set of joint angles
        dthetamat (np.array): N x n matrix of joint velocities (rad/s). Each row is a set of joint velocities
    """
    # Initialize 
    N = int(t/dt)
    n = len(thetalist)
    thetamat = np.zeros((N + 1, n))
    dthetamat = np.zeros((N + 1, n))
    thetamat[0] = thetalist
    dthetamat[0] = dthetalist

    for i in tqdm(range(N)):
        # Calculate damping
        print(f"Iteration {i}")
        tau_damping = - damping * dthetalist
        # Calculate spring force
        spring_force_vec = calculate_spring_wrench(thetalist, Slist, stiffness, restLength, referencePos_q3(i*dt))
        print(spring_force_vec)
        # Forward dynamics
        i_acc = mr.ForwardDynamics(thetalist, dthetalist, tau_damping, g, spring_force_vec, Mlist, Glist, Slist) 
        i_pos, i_vel = mr.EulerStep(thetalist, dthetalist, i_acc, dt)
        thetamat[i + 1] = i_pos
        dthetamat[i + 1] = i_vel

        # Update
        thetalist = i_pos
        dthetalist = i_vel
    
    return thetamat, dthetamat

def referencePos_q3(t):
    """
    Generate a reference position for springPos 

    Args:
        t (float): current time (s)
    Returns:
        np.array: 3-vector of reference position
    """
    return np.array([0, 1, 1])

def calculate_spring_wrench(thetalist, Slist, stiffness, restLength, springPos):
    """
    Calculate the 6-vector spring wrench acting on the end-effector.

    Args:
        thetalist (np.array): n-vector of joint angles (rad)
        Mlist (np.array): 8 frames of link configuration at home pose
        stiffness (float): spring stiffness coefficient (N/m)
        restLength (float): length of the spring at rest (m)
        springPOs (np.array): 3-vector of spring position in {s} frame
    Returns:
        np.array: 6-vector of spring forces and torque acting on the robot. Expressed in end-effector frame.
    """
    # Get end effector transformation matrix for current configuration

    eePos = mr.FKinSpace(ur5.M_EE, Slist, thetalist)
    print(f"eePos = {eePos}")
    # Extract position vector (first 3 elements of last column)
    p = np.array(eePos[:3,3])

    # Calculate spring length
    spring_length = np.linalg.norm(p - springPos) - restLength
    print(f"spring_length = {spring_length}")
    print(f"expected spring force = {stiffness * spring_length}")

    # Calculate spring force vector in {s} frame
    spring_force = stiffness * spring_length * (springPos - p) / np.linalg.norm(p - springPos)
    print(f"spring_force = {spring_force}")
    print(f"norm = {np.linalg.norm(spring_force)}")

    # Convert to end effector frame: T_{ee}^{s} * F_{s}
    spring_force_ee = mr.TransInv(eePos) @ np.array([*spring_force, 1]).T
    print(f"spring_force_ee = {spring_force_ee}")
    print(f"norm = {np.linalg.norm(spring_force_ee[:3])}")

    spring_wrench_ee = np.array([0, 0, 0, *spring_force_ee[:3]])
    return spring_wrench_ee

In [70]:
q3_thetalist0 = np.array([0, 0, 0, 0, 0, 0])
q3_dthetalist0 = np.array([0, 0, 0, 0, 0, 0])
g_q3 = np.array([0, 0, 0])

q3_thetamat, _ = puppet_q3(q3_thetalist0, q3_dthetalist0, g_q3, ur5.Mlist, ur5.Slist, ur5.Glist, 10, 0.01, 0, 10, 0)
# Save to csv file
print(q3_thetamat)
np.savetxt('q3_thetamat.csv', q3_thetamat, delimiter=',')

  2%|▏         | 15/1000 [00:00<00:06, 145.27it/s]

Iteration 0
eePos = [[-1.        0.        0.        0.81725 ]
 [ 0.        0.        1.        0.19145 ]
 [ 0.        1.        0.       -0.005491]
 [ 0.        0.        0.        1.      ]]
spring_length = 1.5273057375918548
expected spring force = 15.273057375918548
spring_force = [-8.1725   8.0855  10.05491]
norm = 15.273057375918548
spring_force_ee = [ 8.98975  10.060401  7.89405   1.      ]
norm = 15.631484214424455
[ 0.        0.        0.        8.98975  10.060401  7.89405 ]
Iteration 1
eePos = [[-1.        0.        0.        0.81725 ]
 [ 0.        0.        1.        0.19145 ]
 [ 0.        1.        0.       -0.005491]
 [ 0.        0.        0.        1.      ]]
spring_length = 1.5273057375918548
expected spring force = 15.273057375918548
spring_force = [-8.1725   8.0855  10.05491]
norm = 15.273057375918548
spring_force_ee = [ 8.98975  10.060401  7.89405   1.      ]
norm = 15.631484214424455
[ 0.        0.        0.        8.98975  10.060401  7.89405 ]
Iteration 2
eePos = [[

  4%|▍         | 45/1000 [00:00<00:06, 141.42it/s]

Iteration 29
eePos = [[-9.93095858e-01 -7.03114464e-04  1.17303545e-01  8.33499591e-01]
 [ 1.17305632e-01 -6.53504644e-03  9.93074359e-01  1.29633958e-01]
 [ 6.83391669e-05  9.99978399e-01  6.57240684e-03 -1.05945117e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
spring_length = 1.6356568147034631
expected spring force = 16.356568147034633
spring_force = [-8.33499591  8.70366042 11.05945117]
norm = 16.356568147034633
spring_force_ee = [10.11173953 11.11556994  7.51253234  1.        ]
norm = 16.80003909474958
[ 0.          0.          0.         10.11173953 11.11556994  7.51253234]
Iteration 30
eePos = [[-9.92091147e-01 -8.59109741e-04  1.25516602e-01  8.33594876e-01]
 [ 1.25519515e-01 -7.45023172e-03  9.92063176e-01  1.25110334e-01]
 [ 8.28366312e-05  9.99971878e-01  7.49914398e-03 -1.12604581e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
spring_length = 1.6426202542261736
expected spring force = 16.426202542261738
spring_force = [-8

  8%|▊         | 75/1000 [00:00<00:06, 140.72it/s]

Iteration 58
eePos = [[-0.89948247 -0.0294896   0.4359606   0.77718673]
 [ 0.43694869 -0.06679994  0.89700257 -0.06801329]
 [ 0.0026699   0.9973305   0.07297082 -0.32659042]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8720346463488087
expected spring force = 18.720346463488088
spring_force = [-7.77186725 10.68013287 13.26590415]
norm = 18.720346463488088
spring_force_ee = [12.42240312 13.09034206  6.90591947  1.        ]
norm = 19.322651948414688
[ 0.          0.          0.         12.42240312 13.09034206  6.90591947]
Iteration 59
eePos = [[-0.89296083 -0.03177641  0.44901138  0.77310058]
 [ 0.45012504 -0.06946389  0.89025964 -0.07734604]
 [ 0.00290082  0.99707825  0.07633189 -0.33420574]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8810805283440737
expected spring force = 18.810805283440736
spring_force = [-7.73100583 10.77346036 13.34205741]
norm = 18.810805283440736
spring_force_ee = [12.51772585 13.15279529  6.88552939  1.        

 10%|█         | 105/1000 [00:00<00:06, 141.56it/s]

Iteration 87
eePos = [[-0.54353251 -0.09499358  0.83399558  0.57833443]
 [ 0.8391257  -0.08633517  0.53704218 -0.42114699]
 [ 0.02098759  0.99172701  0.12663752 -0.50482346]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1490982106776717
expected spring force = 21.490982106776716
spring_force = [-5.78334425 14.21146994 15.04823456]
norm = 21.490982106776716
spring_force_ee = [16.06280523 14.7653969   4.52232131  1.        ]
norm = 22.28187710942753
[ 0.          0.          0.         16.06280523 14.7653969   4.52232131]
Iteration 88
eePos = [[-0.52261394 -0.09501335  0.8472586   0.56560901]
 [ 0.85227825 -0.08419359  0.51626856 -0.43550897]
 [ 0.02228134  0.99190922  0.12497856 -0.50736067]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.157020107920905
expected spring force = 21.57020107920905
spring_force = [-5.65609012 14.35508968 15.07360672]
norm = 21.570201079209053
spring_force_ee = [16.20441696 14.80077612  4.31181985  1.        ]
n

 14%|█▎        | 135/1000 [00:00<00:06, 133.24it/s]

Iteration 116
eePos = [[ 0.27370773  0.03603847  0.96113751 -0.02212482]
 [ 0.95979545 -0.07492447 -0.27051621 -0.67424488]
 [ 0.06226373  0.99653778 -0.05509697 -0.48874619]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.2405246361195568
expected spring force = 22.405246361195566
spring_force = [ 0.22124817 16.74244879 14.88746191]
norm = 22.405246361195566
spring_force_ee = [17.74045645 14.02680654 -5.32476551  1.        ]
norm = 23.23420376302495
[ 0.          0.          0.         17.74045645 14.02680654 -5.32476551]
Iteration 117
eePos = [[ 0.30025869  0.04097841  0.95297717 -0.04613233]
 [ 0.95176182 -0.07906634 -0.29647588 -0.67507197]
 [ 0.06319931  0.99602675 -0.06274204 -0.48814103]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.241106430353558
expected spring force = 22.41106430353558
spring_force = [ 0.46132327 16.75071971 14.88141033]
norm = 22.41106430353558
spring_force_ee = [17.70891623 13.95148535 -5.64705039  1.        ]


 16%|█▋        | 165/1000 [00:01<00:06, 137.48it/s]

Iteration 142
eePos = [[ 0.73084282  0.02809235  0.68196744 -0.48852478]
 [ 0.67662166 -0.1611748  -0.71847464 -0.54528406]
 [ 0.08973233  0.98652598 -0.13680134 -0.44632897]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1721940022068145
expected spring force = 21.721940022068146
spring_force = [ 4.88524781 15.45284059 14.46328973]
norm = 21.721940022068146
spring_force_ee = [16.08993564 12.28119352 -9.86916465  1.        ]
norm = 22.519195235604947
[ 0.          0.          0.         16.08993564 12.28119352 -9.86916465]
Iteration 143
eePos = [[ 0.74219959  0.02420683  0.66974159 -0.4977912 ]
 [ 0.66399231 -0.16203521 -0.72997179 -0.53484069]
 [ 0.09085142  0.98648802 -0.13633562 -0.43999557]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1626648539005178
expected spring force = 21.626648539005178
spring_force = [ 4.97791198 15.34840692 14.39995571]
norm = 21.626648539005174
spring_force_ee = [15.95864947 12.19833824 -9.95023041  1.      

 20%|█▉        | 195/1000 [00:01<00:05, 139.77it/s]

Iteration 171
eePos = [[ 0.96468802 -0.08763192  0.24839014 -0.69771168]
 [ 0.23911673 -0.1040906  -0.96539543 -0.2511396 ]
 [ 0.11045454  0.99069965 -0.0794607  -0.18329848]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8580492935035249
expected spring force = 18.58049293503525
spring_force = [ 6.97711678 12.51139599 11.83298481]
norm = 18.58049293503525
spring_force_ee = [ 11.78280388   9.90350769 -11.36936404   1.        ]
norm = 19.135735435849398
[  0.           0.           0.          11.78280388   9.90350769
 -11.36936404]
Iteration 172
eePos = [[ 0.96888911 -0.09051667  0.2303489  -0.7043448 ]
 [ 0.22138825 -0.099093   -0.97013804 -0.24194654]
 [ 0.11063963  0.99095273 -0.0759708  -0.17332769]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8480342758583108
expected spring force = 18.48034275858311
spring_force = [ 7.04344799 12.41946542 11.73327693]
norm = 18.48034275858311
spring_force_ee = [ 11.62718225   9.84292063 -11.40317613

 22%|██▎       | 225/1000 [00:01<00:05, 141.08it/s]

Iteration 200
eePos = [[ 0.94177629 -0.07846991 -0.32695548 -0.84718265]
 [-0.32103739  0.07923511 -0.94374615 -0.03080216]
 [ 0.09996203  0.99376268  0.04942997  0.09117024]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.614386281509575
expected spring force = 16.14386281509575
spring_force = [ 8.47182646 10.30802161  9.08829761]
norm = 16.14386281509575
spring_force_ee = [  6.35664396   9.02894544 -12.35939847   1.        ]
norm = 16.573578632464468
[  0.           0.           0.           6.35664396   9.02894544
 -12.35939847]
Iteration 201
eePos = [[ 0.9348823  -0.07413882 -0.34712898 -0.85013515]
 [-0.34086139  0.08534961 -0.93623125 -0.02549012]
 [ 0.0990384   0.99358889  0.05452077  0.09925232]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.6080131019740125
expected spring force = 16.080131019740126
spring_force = [ 8.50135154 10.25490115  9.00747678]
norm = 16.080131019740122
spring_force_ee = [  6.12060725   9.03523198 -12.3853123

 26%|██▌       | 255/1000 [00:01<00:05, 141.24it/s]

Iteration 229
eePos = [[ 0.57753014  0.11959629 -0.80756155 -0.87829938]
 [-0.81420699  0.15633402 -0.55913027  0.05026169]
 [ 0.05937944  0.98043684  0.18766375  0.23808242]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.5013097767506178
expected spring force = 15.013097767506178
spring_force = [8.7829938  9.49738305 7.61917579]
norm = 15.013097767506178
spring_force_ee = [ -1.67393902   9.8690572  -11.69909677   1.        ]
norm = 15.397052545415177
[  0.           0.           0.          -1.67393902   9.8690572
 -11.69909677]
Iteration 230
eePos = [[ 0.56010438  0.12701779 -0.81862663 -0.8784085 ]
 [-0.82642803  0.15419262 -0.54151763  0.05053588]
 [ 0.05744381  0.97984239  0.19133503  0.23940108]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.5005313486116918
expected spring force = 15.005313486116918
spring_force = [8.78408503 9.49464118 7.60598921]
norm = 15.005313486116918
spring_force_ee = [ -1.96970346   9.90161531 -11.61463772   

 28%|██▊       | 285/1000 [00:02<00:05, 141.70it/s]

Iteration 258
eePos = [[ 0.06104872  0.22493849 -0.9724586  -0.90299539]
 [-0.99796577 -0.00417313 -0.06361528 -0.00660607]
 [-0.01836772  0.97436403  0.22422615  0.17055418]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.5863911352101445
expected spring force = 15.863911352101445
spring_force = [ 9.02995391 10.06606073  8.29445822]
norm = 15.863911352101447
spring_force_ee = [-9.59500052 10.10790794 -8.47856576  1.        ]
norm = 16.31318225255075
[ 0.          0.          0.         -9.59500052 10.10790794 -8.47856576]
Iteration 259
eePos = [[ 0.04552402  0.22348677 -0.97364328 -0.90451293]
 [-0.99871994 -0.01132779 -0.04929665 -0.0111927 ]
 [-0.02204637  0.97464114  0.22268501  0.16407922]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.5935550987637495
expected spring force = 15.935550987637495
spring_force = [ 9.04512927 10.11192697  8.35920779]
norm = 15.935550987637495
spring_force_ee = [-9.83788665 10.09625027 -8.36150587  1.       

 32%|███▏      | 315/1000 [00:02<00:04, 141.49it/s]

Iteration 287
eePos = [[-0.22433146  0.09903219 -0.96946791 -0.86111763]
 [-0.96193629 -0.1818129   0.20401629 -0.21337115]
 [-0.15605759  0.97833363  0.13604901 -0.13617843]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8720829376716344
expected spring force = 18.720829376716345
spring_force = [ 8.6111763  12.13371146 11.36178426]
norm = 18.720829376716342
spring_force_ee = [-15.79638468   9.94204674  -5.0997926    1.        ]
norm = 19.34884872571138
[  0.           0.           0.         -15.79638468   9.94204674
  -5.0997926 ]
Iteration 288
eePos = [[-0.22737584  0.09360349 -0.969298   -0.8534921 ]
 [-0.96026519 -0.18697151  0.20720142 -0.2223086 ]
 [-0.16183634  0.97789572  0.13239698 -0.14959683]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8825673838752661
expected spring force = 18.82567383875266
spring_force = [ 8.53492104 12.22308602 11.49596827]
norm = 18.82567383875266
spring_force_ee = [-15.97025312   9.94000227  -4.9796290

 33%|███▎      | 330/1000 [00:02<00:04, 139.96it/s]

Iteration 316
eePos = [[-0.12312052  0.00325981 -0.99238637 -0.51203221]
 [-0.93298432 -0.34117474  0.1146301  -0.45695147]
 [-0.33820349  0.93999424  0.04504697 -0.4796472 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.138747389937341
expected spring force = 21.38747389937341
spring_force = [ 5.12032209 14.56951468 14.79647199]
norm = 21.387473899373408
spring_force_ee = [-19.87935246   9.25117384  -3.17884349   1.        ]
norm = 22.155764881152834
[  0.           0.           0.         -19.87935246   9.25117384
  -3.17884349]
Iteration 317
eePos = [[-0.11289903  0.0039916  -0.99359845 -0.49786924]
 [-0.9319418  -0.34722412  0.1044983  -0.46458007]
 [-0.34458423  0.93777368  0.0429212  -0.48886174]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.146992745792989
expected spring force = 21.46992745792989
spring_force = [ 4.97869239 14.64580073 14.8886174 ]
norm = 21.46992745792989
spring_force_ee = [-19.99913081   9.19576675  -3.20247414 

 36%|███▌      | 360/1000 [00:02<00:04, 139.31it/s]

Iteration 345
eePos = [[ 0.30910535  0.21259527 -0.92696124 -0.02019783]
 [-0.81500984 -0.44309601 -0.37339643 -0.59952417]
 [-0.49011514  0.87090136  0.03630389 -0.5724701 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.243111176454507
expected spring force = 22.43111176454507
spring_force = [ 0.20197825 15.99524174 15.72470099]
norm = 22.43111176454507
spring_force_ee = [-21.4437119    6.88738753  -5.81072427   1.        ]
norm = 23.2601247571874
[  0.           0.           0.         -21.4437119    6.88738753
  -5.81072427]
Iteration 346
eePos = [[ 3.27601152e-01  2.25782775e-01 -9.17441891e-01  9.57507603e-04]
 [-8.05803348e-01 -4.40230752e-01 -3.96078084e-01 -5.98411377e-01]
 [-4.93313743e-01  8.69033385e-01  3.77164143e-02 -5.69646600e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
spring_length = 2.2402478196855364
expected spring force = 22.402478196855363
spring_force = [-9.57507603e-03  1.59841138e+01  1.56964660e+01]
norm = 2

 39%|███▉      | 389/1000 [00:02<00:04, 136.85it/s]

Iteration 373
eePos = [[ 0.80694998  0.48657468 -0.33477876  0.55875688]
 [-0.34171675 -0.07768785 -0.93658649 -0.4135856 ]
 [-0.48172752  0.87017796  0.10358051 -0.48679363]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.126261693947547
expected spring force = 21.26261693947547
spring_force = [-5.58756879 14.13585597 14.86793631]
norm = 21.26261693947547
spring_force_ee = [-17.32836115   9.24038621  -9.97870048   1.        ]
norm = 22.027966331722286
[  0.           0.           0.         -17.32836115   9.24038621
  -9.97870048]
Iteration 374
eePos = [[ 0.82004484  0.48607369 -0.30209076  0.57497446]
 [-0.3165313  -0.05454697 -0.94701244 -0.40206237]
 [-0.47679596  0.87221385  0.10912657 -0.48324491]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1204692871695805
expected spring force = 21.204692871695805
spring_force = [-5.74974461 14.02062371 14.83244914]
norm = 21.204692871695805
spring_force_ee = [-17.05424599   9.49756709 -10.0764747

 42%|████▏     | 417/1000 [00:02<00:04, 135.83it/s]

eePos = [[ 0.84258995  0.02664117  0.53789629  0.77684157]
 [ 0.48302264  0.4043386  -0.77665915 -0.0794545 ]
 [-0.23818334  0.91422128  0.32782335 -0.30328547]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8620574240851198
expected spring force = 18.620574240851198
spring_force = [-7.76841575 10.79454498 13.03285466]
norm = 18.620574240851198
spring_force_ee = [-5.12420646 16.36130511 -8.66995524  1.        ]
norm = 19.212441820877757
[ 0.          0.          0.         -5.12420646 16.36130511 -8.66995524]
Iteration 401
eePos = [[ 0.82599965 -0.00234376  0.56366576  0.77939226]
 [ 0.51647663  0.40369603 -0.75516978 -0.06821977]
 [-0.2257797   0.91489017  0.33466327 -0.29441619]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8504213138799952
expected spring force = 18.50421313879995
spring_force = [-7.79392258 10.68219771 12.94416188]
norm = 18.504213138799955
spring_force_ee = [-4.51821775 16.47183955 -8.52040861  1.        ]
norm = 19.0

 45%|████▍     | 446/1000 [00:03<00:03, 138.51it/s]

Iteration 428
eePos = [[-0.0284652  -0.28807092  0.95718592  0.80833683]
 [ 0.98467859 -0.17288884 -0.02274915  0.1768433 ]
 [ 0.17204013  0.94187292  0.28857858 -0.09230615]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.588750484618568
expected spring force = 15.887504846185681
spring_force = [-8.08336831  8.23156697 10.92306148]
norm = 15.887504846185681
spring_force_ee = [10.07950341 11.54394633 -5.51545392  1.        ]
norm = 16.287397514393888
[ 0.          0.          0.         10.07950341 11.54394633 -5.51545392]
Iteration 429
eePos = [[-0.06016432 -0.27154312  0.9605439   0.80820171]
 [ 0.98012482 -0.1983102   0.00532904  0.18356833]
 [ 0.18903859  0.94177354  0.27807735 -0.08663682]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.581306501023014
expected spring force = 15.81306501023014
spring_force = [-8.08201708  8.16431666 10.86636823]
norm = 15.81306501023014
spring_force_ee = [10.42754417 11.14666423 -5.45113314  1.        ]


 48%|████▊     | 476/1000 [00:03<00:03, 139.84it/s]

Iteration 457
eePos = [[-0.44039584  0.46656768  0.76705026  0.77928729]
 [ 0.63167617 -0.44610098  0.63401824  0.2936637 ]
 [ 0.63799429  0.76374637 -0.09825867  0.01946837]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.4379297346257658
expected spring force = 14.379297346257658
spring_force = [-7.79287293  7.06336298  9.80531627]
norm = 14.379297346257658
spring_force_ee = [14.29471653  0.45444341 -3.24470934  1.        ]
norm = 14.665387079035893
[ 0.          0.          0.         14.29471653  0.45444341 -3.24470934]
Iteration 458
eePos = [[-0.43891391  0.49051775  0.75282595  0.77782863]
 [ 0.61929879 -0.44190098  0.64899348  0.29482242]
 [ 0.65101735  0.75107647 -0.10982057  0.02146041]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.435211660635042
expected spring force = 14.352116606350421
spring_force = [-7.77828626  7.0517758   9.78539585]
norm = 14.352116606350421
spring_force_ee = [14.29646225  0.15063157 -3.12832759  1.       

 51%|█████     | 506/1000 [00:03<00:03, 138.98it/s]

Iteration 486
eePos = [[-0.23028778  0.88995829  0.39362644  0.75501534]
 [ 0.36164606 -0.29725887  0.88365677  0.26166022]
 [ 0.90342662  0.34584881 -0.25339483  0.02170716]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.439531412896875
expected spring force = 14.39531412896875
spring_force = [-7.55015341  7.38339783  9.78292844]
norm = 14.395314128968748
spring_force_ee = [13.30667446 -6.13234669  0.5505947   1.        ]
norm = 14.66207405327342
[ 0.          0.          0.         13.30667446 -6.13234669  0.5505947 ]
Iteration 487
eePos = [[-0.2196038   0.89596324  0.38603631  0.75514995]
 [ 0.35476278 -0.29526729  0.887108    0.25835987]
 [ 0.90880006  0.3317636  -0.25301259  0.01943789]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.4428387192354686
expected spring force = 14.428387192354686
spring_force = [-7.55149945  7.41640132  9.80562106]
norm = 14.428387192354684
spring_force_ee = [13.25726229 -6.30928867  0.66725999  1.        ]

 54%|█████▎    | 535/1000 [00:03<00:03, 139.91it/s]

Iteration 514
eePos = [[ 0.08974408  0.91497659  0.39340034  0.77442847]
 [ 0.18402123 -0.40342671  0.89631639  0.11623856]
 [ 0.97881673 -0.00804508 -0.20458028 -0.1130384 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.6185265539523659
expected spring force = 16.18526553952366
spring_force = [-7.74428471  8.83761437 11.13038396]
norm = 16.185265539523662
spring_force_ee = [ 11.84566407 -11.40331332   2.16566493   1.        ]
norm = 16.58449325654893
[  0.           0.           0.          11.84566407 -11.40331332
   2.16566493]
Iteration 515
eePos = [[ 0.10106767  0.91028127  0.40146398  0.77517377]
 [ 0.17686275 -0.41354191  0.89314201  0.10890851]
 [ 0.97903263 -0.01926376 -0.20279057 -0.1205304 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.628043851459915
expected spring force = 16.280438514599147
spring_force = [-7.75173766  8.91091492 11.20530395]
norm = 16.280438514599147
spring_force_ee = [ 11.78331336 -11.62006451   2.1414215

 56%|█████▋    | 565/1000 [00:04<00:03, 140.46it/s]

Iteration 543
eePos = [[ 0.28238865  0.53947628  0.79323514  0.74934929]
 [-0.19757816 -0.77645351  0.59840022 -0.16569629]
 [ 0.93873293 -0.32570738 -0.11267293 -0.36958868]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.948369922376485
expected spring force = 19.48369922376485
spring_force = [-7.49349294 11.6569629  13.69588679]
norm = 19.48369922376485
spring_force_ee = [  8.54014061 -18.20779215  -1.04862855   1.        ]
norm = 20.138453728224423
[  0.           0.           0.           8.54014061 -18.20779215
  -1.04862855]
Iteration 544
eePos = [[ 0.27824295  0.5171415   0.80941061  0.74518496]
 [-0.22000873 -0.78597     0.57779522 -0.17806587]
 [ 0.93497434 -0.33884484 -0.10491497 -0.37842317]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.9604056321817107
expected spring force = 19.604056321817108
spring_force = [-7.45184958 11.78065868 13.78423168]
norm = 19.604056321817108
spring_force_ee = [  8.32992806 -18.43716805  -1.2109472

 60%|█████▉    | 595/1000 [00:04<00:02, 140.68it/s]

Iteration 572
eePos = [[-0.33781192  0.12410541  0.93299569  0.41551293]
 [-0.8103984  -0.5424922  -0.22126149 -0.54215054]
 [ 0.47868313 -0.83084298  0.28383516 -0.54638678]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.223103990868124
expected spring force = 22.23103990868124
spring_force = [-4.15512925 15.42150541 15.46386779]
norm = 22.23103990868124
spring_force_ee = [ -3.72906499 -22.52940791  -3.25225867   1.        ]
norm = 23.066368002077805
[  0.           0.           0.          -3.72906499 -22.52940791
  -3.25225867]
Iteration 573
eePos = [[-0.36807101  0.13144801  0.92045921  0.39478473]
 [-0.8163959  -0.51947645 -0.25227356 -0.55295561]
 [ 0.44499603 -0.84431371  0.29851784 -0.54918368]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.228788052028875
expected spring force = 22.287880520288752
spring_force = [-3.94784735 15.52955612 15.49183676]
norm = 22.287880520288752
spring_force_ee = [ -4.39310931 -22.46896991  -3.26587739

 62%|██████▎   | 625/1000 [00:04<00:02, 140.89it/s]

Iteration 601
eePos = [[-0.71152852  0.69846802  0.07661322 -0.29542906]
 [-0.38714785 -0.29870769 -0.87229024 -0.62238631]
 [-0.58638188 -0.65032003  0.48294944 -0.5405658 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.2567141274789093
expected spring force = 22.567141274789094
spring_force = [ 2.95429057 16.22386308 15.40565802]
norm = 22.567141274789094
spring_force_ee = [-18.18483411 -13.13242775  -6.74462753   1.        ]
norm = 23.423041019364902
[  0.           0.           0.         -18.18483411 -13.13242775
  -6.74462753]
Iteration 602
eePos = [[-0.70208412  0.71126882  0.03427174 -0.31816762]
 [-0.3619023  -0.31495239 -0.87740054 -0.61620499]
 [-0.61327368 -0.62841202  0.4785329  -0.53677965]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.2527851390556046
expected spring force = 22.527851390556044
spring_force = [ 3.18167616 16.16204988 15.36779648]
norm = 22.527851390556044
spring_force_ee = [-18.28313173 -12.78964851  -6.9904

 66%|██████▌   | 655/1000 [00:04<00:02, 140.88it/s]

Iteration 630
eePos = [[-0.12883152  0.47109996 -0.87262092 -0.75114445]
 [ 0.35247331 -0.80074024 -0.48433215 -0.33446768]
 [-0.92691154 -0.36997283 -0.06288959 -0.32393202]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.0243067888930817
expected spring force = 20.243067888930817
spring_force = [ 7.51144449 13.34467683 13.2393202 ]
norm = 20.243067888930817
spring_force_ee = [ -8.81488346 -12.07897095 -14.68834477   1.        ]
norm = 20.960705655190857
[  0.           0.           0.          -8.81488346 -12.07897095
 -14.68834477]
Iteration 631
eePos = [[-0.09942651  0.45534903 -0.88474382 -0.75929033]
 [ 0.37702562 -0.8056116  -0.45699195 -0.32282365]
 [-0.92085072 -0.3790082  -0.0915791  -0.31301062]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.0125558650296944
expected spring force = 20.125558650296945
spring_force = [ 7.59290334 13.22823648 13.13010622]
norm = 20.12555865029695
spring_force_ee = [ -8.10043655 -12.20877943 -14.81338

 68%|██████▊   | 685/1000 [00:04<00:02, 139.74it/s]

Iteration 659
eePos = [[ 0.58318573  0.43310023 -0.68725439 -0.81119204]
 [ 0.75175475 -0.60833068  0.25455565 -0.03400219]
 [-0.30782982 -0.66509997 -0.68035493  0.01670315]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.6413609415518566
expected spring force = 16.413609415518565
spring_force = [ 8.11192041 10.34002189  9.83296845]
norm = 16.413609415518565
spring_force_ee = [  9.98081456  -8.97503284 -10.17022625   1.        ]
norm = 16.840468397222075
[  0.           0.           0.           9.98081456  -8.97503284
 -10.17022625]
Iteration 660
eePos = [[ 0.59475338  0.44385986 -0.67026625 -0.80858004]
 [ 0.75378625 -0.59770007  0.27305843 -0.0259771 ]
 [-0.27941851 -0.66763991 -0.6900596   0.02720053]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.62873248161595
expected spring force = 16.2873248161595
spring_force = [ 8.08580044 10.25977097  9.72799468]
norm = 16.2873248161595
spring_force_ee = [10.33263691 -8.67657126 -9.84711888  1. 

 71%|███████▏  | 713/1000 [00:05<00:02, 139.21it/s]

Iteration 687
eePos = [[ 0.60590342  0.73710933 -0.29925054 -0.72781393]
 [ 0.73185403 -0.36899111  0.57291817  0.1242133 ]
 [ 0.31188254 -0.5661408  -0.76302941  0.21732961]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.381770026714897
expected spring force = 13.817700267148968
spring_force = [7.27813933 8.75786703 7.82670389]
norm = 13.817700267148968
spring_force_ee = [13.54263975 -1.59245584 -3.25558507  1.        ]
norm = 14.019195454796506
[ 0.          0.          0.         13.54263975 -1.59245584 -3.25558507]
Iteration 688
eePos = [[ 0.5988964   0.7459282  -0.29140044 -0.72559321]
 [ 0.73147047 -0.36140418  0.57821966  0.12761415]
 [ 0.32599701 -0.55944449 -0.76206811  0.22075372]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.3765054801841128
expected spring force = 13.765054801841128
spring_force = [7.25593207 8.72385848 7.79246282]
norm = 13.76505480184113
spring_force_ee = [13.53636018 -1.38902475 -3.12546062  1.        ]
norm

 74%|███████▍  | 742/1000 [00:05<00:01, 139.49it/s]

eePos = [[ 0.32568558  0.90402821 -0.27687886 -0.69857518]
 [ 0.77388464 -0.08665378  0.62737045  0.16918441]
 [ 0.54316798 -0.41859781 -0.72783543  0.21968464]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.336844749497808
expected spring force = 13.36844749497808
spring_force = [6.9857518  8.3081559  7.80315358]
norm = 13.368447494978078
spring_force_ee = [12.9203971   3.06715223 -2.54099489  1.        ]
norm = 13.520382359349483
[ 0.          0.          0.         12.9203971   3.06715223 -2.54099489]
Iteration 716
eePos = [[ 0.31343865  0.90621508 -0.28377886 -0.69854771]
 [ 0.77641192 -0.07249941  0.62604183  0.16878182]
 [ 0.54675475 -0.41655499 -0.72632031  0.21634033]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.3390351140335812
expected spring force = 13.390351140335813
spring_force = [6.98547708 8.31218181 7.83659666]
norm = 13.390351140335811
spring_force_ee = [12.89751442  3.1987316  -2.61720169  1.        ]
norm = 13.54354114

 77%|███████▋  | 772/1000 [00:05<00:01, 140.05it/s]

Iteration 744
eePos = [[-0.03188428  0.74729742 -0.66372431 -0.70622139]
 [ 0.78114352  0.43290899  0.44989399  0.08915117]
 [ 0.62353684 -0.5041194  -0.59754953  0.04756929]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.4951650383100996
expected spring force = 14.951650383100997
spring_force = [7.06221387 9.10848826 9.52430712]
norm = 14.951650383100997
spring_force_ee = [12.70680089  4.93247644 -6.76117408  1.        ]
norm = 15.215307676033634
[ 0.          0.          0.         12.70680089  4.93247644 -6.76117408]
Iteration 745
eePos = [[-0.0424105   0.73062745 -0.6814579  -0.70633518]
 [ 0.777651    0.45236424  0.43660682  0.08363017]
 [ 0.62726412 -0.51141971 -0.58735816  0.03955998]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.5036914834580941
expected spring force = 15.03691483458094
spring_force = [7.06335177 9.16369826 9.60440022]
norm = 15.03691483458094
spring_force_ee = [12.73128883  4.89259695 -6.94828184  1.        ]
norm

 79%|███████▊  | 787/1000 [00:05<00:01, 140.03it/s]

Iteration 773
eePos = [[-0.19611751 -0.09192662 -0.97626196 -0.67735539]
 [ 0.60007084  0.77615864 -0.19363044 -0.1438154 ]
 [ 0.77553395 -0.62380066 -0.09705581 -0.19721184]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.7889774128730993
expected spring force = 17.88977412873099
spring_force = [ 6.77355391 11.43815402 11.97211838]
norm = 17.889774128730995
spring_force_ee = [ 14.92647714   0.7132726  -10.69776543   1.        ]
norm = 18.37799398623869
[  0.           0.           0.          14.92647714   0.7132726
 -10.69776543]
Iteration 774
eePos = [[-0.19642818 -0.12973534 -0.97189748 -0.67491096]
 [ 0.59246216  0.77409756 -0.22307299 -0.15407613]
 [ 0.78128392 -0.6196303  -0.0751913  -0.20570416]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.8003108221257422
expected spring force = 18.00310822125742
spring_force = [ 6.74910962 11.54076134 12.05704162]
norm = 18.00310822125742
spring_force_ee = [ 15.05114786   0.49141847 -10.74624099 

 82%|████████▏ | 817/1000 [00:05<00:01, 140.20it/s]

Iteration 802
eePos = [[-0.13830956 -0.9452878  -0.29546818 -0.56672932]
 [ 0.38662984  0.22312874 -0.8948357  -0.47580514]
 [ 0.91180471 -0.23800114  0.33461563 -0.44737761]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1433816496873495
expected spring force = 21.433816496873494
spring_force = [ 5.66729315 14.75805144 14.47377614]
norm = 21.433816496873494
spring_force_ee = [ 18.63281698  -6.0450858  -10.48090268   1.        ]
norm = 22.216531047275954
[  0.           0.           0.          18.63281698  -6.0450858
 -10.48090268]
Iteration 803
eePos = [[-0.13554789 -0.95692313 -0.25675842 -0.56008055]
 [ 0.37877224  0.1894149  -0.90589932 -0.48766919]
 [ 0.91550989 -0.2200457   0.33678113 -0.45408318]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.154346245967937
expected spring force = 21.54346245967937
spring_force = [ 5.6008055  14.87669192 14.54083182]
norm = 21.54346245967937
spring_force_ee = [ 18.71249138  -6.28482204 -10.4504193 

 85%|████████▍ | 846/1000 [00:06<00:01, 134.02it/s]

Iteration 831
eePos = [[-0.07578452 -0.61682049  0.78344699 -0.05223269]
 [ 0.16843168 -0.78233496 -0.59965222 -0.59796765]
 [ 0.98279574  0.08651294  0.16318099 -0.46241862]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1667711208564464
expected spring force = 21.667711208564462
spring_force = [ 0.52232686 15.97967654 14.62418617]
norm = 21.66771120856446
spring_force_ee = [ 17.57570872 -12.01848423  -7.02883699   1.        ]
norm = 22.422177635862532
[  0.           0.           0.          17.57570872 -12.01848423
  -7.02883699]
Iteration 832
eePos = [[-0.07661048 -0.58171002  0.80978039 -0.02703289]
 [ 0.16441326 -0.80841958 -0.56517791 -0.59457517]
 [ 0.98341198  0.08984008  0.15757425 -0.46387823]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.164795656287583
expected spring force = 21.647956562875834
spring_force = [ 0.27032894 15.94575173 14.6387823 ]
norm = 21.647956562875834
spring_force_ee = [ 17.54880522 -12.18767819  -6.727639

 88%|████████▊ | 876/1000 [00:06<00:00, 137.21it/s]

Iteration 857
eePos = [[-0.09951508  0.36841302  0.92432061  0.52034989]
 [ 0.08592256 -0.92228034  0.37685049 -0.33983228]
 [ 0.99131935  0.1169223   0.06012581 -0.56931097]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.1280628414817864
expected spring force = 21.280628414817862
spring_force = [-5.20349889 13.3983228  15.69310967]
norm = 21.280628414817862
spring_force_ee = [ 17.87127909 -12.87773105   0.86435038   1.        ]
norm = 22.044629162042337
[  0.           0.           0.          17.87127909 -12.87773105
   0.86435038]
Iteration 858
eePos = [[-0.09655757  0.39947026  0.91164694  0.53386141]
 [ 0.08363618 -0.909431    0.40735763 -0.32428874]
 [ 0.99180725  0.11558013  0.05440228 -0.57369905]
 [ 0.          0.          0.          1.        ]]
spring_length = 2.124918199878198
expected spring force = 21.24918199878198
spring_force = [-5.33861406 13.24288735 15.7369905 ]
norm = 21.24918199878198
spring_force_ee = [ 17.87879891 -12.79909821   1.0604071

 91%|█████████ | 906/1000 [00:06<00:00, 138.68it/s]

Iteration 886
eePos = [[ 0.01997564  0.92421181  0.38135745  0.56126743]
 [ 0.03353911 -0.38183832  0.92362039  0.06339305]
 [ 0.99923776 -0.00565952 -0.0386247  -0.41128186]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.7843682904733948
expected spring force = 17.84368290473395
spring_force = [-5.61267434  9.36606947 14.1128186 ]
norm = 17.84368290473395
spring_force_ee = [14.70170461 -9.34034772  5.67667385  1.        ]
norm = 18.31957532131079
[ 0.          0.          0.         14.70170461 -9.34034772  5.67667385]
Iteration 887
eePos = [[ 0.02443499  0.93188112  0.36193993  0.55943779]
 [ 0.03202416 -0.36259187  0.93139766  0.07215231]
 [ 0.99918836 -0.01116787 -0.03870264 -0.4006738 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.77080746259231
expected spring force = 17.7080746259231
spring_force = [-5.59437789  9.27847695 14.00673797]
norm = 17.7080746259231
spring_force_ee = [14.54017459 -9.23366314  5.7898327   1.        ]
norm 

 93%|█████████▎| 934/1000 [00:06<00:00, 137.73it/s]

Iteration 914
eePos = [[ 0.15162911  0.9876141  -0.04033613  0.57274995]
 [ 0.02699253  0.03665548  0.99896335  0.25241121]
 [ 0.98806883 -0.15256069 -0.02110016 -0.13696069]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.4763506112300169
expected spring force = 14.763506112300169
spring_force = [-5.72749954  7.47588794 11.36960691]
norm = 14.763506112300169
spring_force_ee = [10.6089595  -7.71288521  7.22732577  1.        ]
norm = 14.975742310136498
[ 0.          0.          0.         10.6089595  -7.71288521  7.22732577]
Iteration 915
eePos = [[ 0.1563918   0.98641303 -0.05030838  0.57480555]
 [ 0.02815619  0.04646197  0.99852317  0.25797322]
 [ 0.98729369 -0.15757732 -0.02050736 -0.12800257]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.4674450480473165
expected spring force = 14.674450480473165
spring_force = [-5.7480555   7.4202678  11.28002573]
norm = 14.674450480473164
spring_force_ee = [10.47589369 -7.70182484  7.23586146  1.      

 96%|█████████▌| 962/1000 [00:06<00:00, 136.97it/s]

Iteration 942
eePos = [[ 0.28287887  0.93775118 -0.20150003  0.63556497]
 [ 0.06560876  0.19067074  0.97945912  0.37946871]
 [ 0.95690911 -0.29028845 -0.00758797  0.08392551]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.2760072053773586
expected spring force = 12.760072053773586
spring_force = [-6.35564969  6.20531289  9.16074494]
norm = 12.760072053773587
spring_force_ee = [ 7.09025072 -8.08009766  7.04603153  1.        ]
norm = 12.853256153737215
[ 0.          0.          0.          7.09025072 -8.08009766  7.04603153]
Iteration 943
eePos = [[ 0.28759597  0.93592162 -0.2033206   0.63782802]
 [ 0.06639637  0.19229548  0.97908834  0.38260799]
 [ 0.95544758 -0.29508161 -0.00683839  0.09026728]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.2710669144168965
expected spring force = 12.710669144168964
spring_force = [-6.37828019  6.17392014  9.09732719]
norm = 12.710669144168966
spring_force_ee = [ 6.9724912  -8.110702    7.03513174  1.      

 99%|█████████▉| 990/1000 [00:07<00:00, 135.89it/s]

Iteration 970
eePos = [[ 0.42023295  0.88847795 -0.18442127  0.70793208]
 [ 0.04569174  0.18226132  0.9821879   0.41971086]
 [ 0.90626516 -0.42117425  0.03599611  0.20582144]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.211867524185271
expected spring force = 12.11867524185271
spring_force = [-7.07932076  5.8028914   7.9417856 ]
norm = 12.11867524185271
spring_force_ee = [ 3.98434147 -9.19584571  7.00189444  1.        ]
norm = 12.225591234062083
[ 0.          0.          0.          3.98434147 -9.19584571  7.00189444]
Iteration 971
eePos = [[ 0.42528865  0.88661517 -0.1817776   0.71113343]
 [ 0.04335547  0.18065814  0.98258992  0.41917141]
 [ 0.90401873 -0.42576539  0.03839224  0.20788516]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.2126493786503043
expected spring force = 12.126493786503044
spring_force = [-7.1113343   5.80828585  7.92114837]
norm = 12.126493786503044
spring_force_ee = [ 3.87977524 -9.24597176  7.01336833  1.        ]

100%|██████████| 1000/1000 [00:07<00:00, 139.05it/s]

Iteration 998
eePos = [[ 0.55881493  0.82630639 -0.07031083  0.81861258]
 [-0.0509557   0.11883657  0.99160546  0.34231482]
 [ 0.82772543 -0.5505412   0.10851267  0.19733775]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.321719729905358
expected spring force = 13.21719729905358
spring_force = [-8.18612581  6.57685182  8.0266225 ]
norm = 13.21719729905358
spring_force_ee = [  1.13083061 -11.01012578   7.66490818   1.        ]
norm = 13.463003560684978
[  0.           0.           0.           1.13083061 -11.01012578
   7.66490818]
Iteration 999
eePos = [[ 0.56351635  0.82357784 -0.06456671  0.82308436]
 [-0.05549833  0.11572306  0.99172986  0.33684555]
 [ 0.82423859 -0.55527265  0.11091903  0.1943221 ]
 [ 0.          0.          0.          1.        ]]
spring_length = 1.3290442331999788
expected spring force = 13.290442331999788
spring_force = [-8.23084361  6.63154448  8.05677905]
norm = 13.290442331999788
spring_force_ee = [  1.02915868 -11.0939799    7.6993193